# Generated by Django 3.2.5 on 2021-07-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_shippingaddress_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
